default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: image_crop_development

test:
  <<: *default
  database: image_crop_test

production:
  <<: *default
  database: image_crop_production
  username: image_crop
  password: <%= ENV['IMAGE_CROP_DATABASE_PASSWORD'] %>
